name: Deploy 3rd party helm chart

on:
  workflow_call:
    inputs:
      repository:
        description: "Repo where the chart is stored"
        required: true
        type: string
      chart_name:
        description: "Name of the chart to deploy"
        required: true
        type: string
      chart_version:
        description: "Version of the helm chart to deploy"
        required: true
        type: string
      values_file_name:
        description: "name of the file with values for the chart"
        required: true
        type: string
      environment:
        description: "Environment to run on"
        required: true
        type: string
    secrets:
      DO_TOKEN:
        required: true

jobs:
  helm-deploy:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install doctl and login
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}

      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save ${{ vars.cluster_name }}

      - name: Deploy ${{ inputs.chart_name}} Helm chart
        if: inputs.rendering == false
        run: helm upgrade --install --atomic --timeout 5m --create-namespace --namespace ${{ vars.namespace }} --values ${{ inputs.values_file_name }} ${{ inputs.chart_name }} ${{ inputs.repository }}/${{ inputs.chart_name }} --version ${{ inputs.chart_version }}

