name: Helm deploy

on:
  workflow_call:
    inputs:
      chart_name:
        description: "Name of the chart to deploy"
        required: true
        type: string
      chart_version:
        description: "Version of the helm chart to deploy"
        required: true
        type: string
      rendering:
        description: "if additional rendering is needed, set this to true. expects "
        required: false
        type: boolean
        default: false
      environment:
        description: "Environment to run on"
        required: true
        type: string
    secrets:
      DO_TOKEN:
        required: true

env:
  REGISTRY: ghcr.io
  REGISTRY_NAMESPACE: toolops

jobs:
  helm-deploy:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl and login
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}

      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save ${{ vars.cluster_name }}

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy Helm chart without additional rendering
        if: inputs.renderer_path == false
        run: helm upgrade --install --atomic --timeout 5m --create-namespace --namespace ${{ vars.namespace }} ${{ inputs.chart_name }} oci://${{ env.REGISTRY }}/${{ env.REGISTRY_NAMESPACE }}/helm/${{ inputs.chart_name }} --version ${{ inputs.chart_version }}

      - name: Create renderer script
        if: inputs.renderer_path == true
        run: |
          cat << EOF > ./renderer.sh
          #!/bin/sh
          envsubst <&0
          EOF
          chmod +x ./renderer.sh

      - name: Deploy Helm chart with additional rendering
        if: inputs.renderer_path == true
        run: helm upgrade --install --atomic --timeout 5m --create-namespace --namespace ${{ vars.namespace }} --post-renderer ./renderer.sh ${{ inputs.chart_name }} oci://${{ env.REGISTRY }}/${{ env.REGISTRY_NAMESPACE }}/helm/${{ inputs.chart_name }} --version ${{ inputs.chart_version }}
    
