name: Helm release

on:
  workflow_call:
    inputs:
      chart_name:
        required: true
        type: string
    secrets:
      DO_API:
        required: true

env:
  REGISTRY: registry.digitalocean.com

permissions:
  contents: write
  packages: write

jobs:
  helm-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Prep git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: bump version
        id: bump
        uses: haya14busa/action-bumpr@v1
        with:
          default_bump_level: patch
          dry_run: true

      - name: bump chart version
        run: |
          export chartVersion=$(cat Chart.yaml | grep '^version:' | awk '{ print $2 }')
          sed -i '/version:/ s/'${chartVersion}'/'${{ steps.bump.outputs.next_version }}'/' Chart.yaml
      
      - name: commit bump
        run: |
          git add Chart.yaml
          git commit -m "bump chart version"
          git push

      - name: Package Helm chart
        run: helm package .

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DO_API }}
          password: ${{ secrets.DO_API }}

      - name: Push Helm chart
        run: helm push ${{ inputs.chart_name }}-${{ steps.bump.outputs.next_version }}.tgz oci://${{ env.REGISTRY }}/${{ github.repository_owner }}

      - name: Creare release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          name: Release ${{ steps.bump.outputs.next_version }}
          tag_name: ${{ steps.bump.outputs.next_version }}
          files: ${{ inputs.chart_name }}-${{ steps.bump.outputs.next_version }}.tgz
