name: Helm linter

on:
  workflow_call:

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Lint chart
        run: helm lint .
