name: Reusable workflows release

on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  release:
    name: Release workflow version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Bump version
        id: bump
        uses: haya14busa/action-bumpr@v1
        with:
          default_bump_level: patch
          dry_run: true

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          name: Release ${{ steps.bump.outputs.next_version }}
          tag_name: ${{ steps.bump.outputs.next_version }}
