name: Terraform apply

on:
  workflow_call:
    secrets:
      TF_API_TOKEN:
        required: true
    inputs:
      environment:
        description: "Environment to run on"
        required: true
        type: string

env:
  TF_CLOUD_ORGANIZATION: ToolOps
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"

permissions:
  contents: read

jobs:
  terraform-apply:
    name: Terraform Apply
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      
    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
    
    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve -input=false -no-color -var "do_token=${{ secrets.DO_TOKEN }}"
